project: viddiff_0
seed: 0
debug: 0
do_eval: 1 
eval_mode: 0

logging: 
  name: gpt-4o_fitness_4fps
  results_dir: lmms/results/${logging.name}/seed_${seed}
  overwrite_ok: True
  verbose: 1 

data:
  split: fitness 
  debug: ${debug}
  eval_mode: ${eval_mode}  
  subset_mode: "8_per_action"

lmm:
  api: openai
  fps: 4
  model: gpt-4o-2024-05-13
  video_representation: frames
  seed: ${seed}
