project: viddiff_0
seed: 0
debug: 0
do_eval: 1 
eval_mode: 2

logging: 
  name: mode2-gemini-pro_surgery_2fps_1geminifps
  results_dir: lmms/results/${logging.name}/seed_${seed}
  overwrite_ok: True
  verbose: 1 

data:
  split: surgery
  debug: ${debug}
  eval_mode: ${eval_mode}  
  subset_mode: "15_per_action"

lmm:
  api: gemini 
  fps: 6
  fps_gemini: 1
  model: models/gemini-1.5-pro
  # model: models/gemini-1.5-flash
  video_representation: video
  seed: ${seed}
